ALTER TABLE invoices ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE clients  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;